supabase.url=https://scwvalydghoynskqliqo.supabase.co
supabase.anon-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjd3ZhbHlkZ2hveW5za3FsaXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNTI3ODIsImV4cCI6MjA5MDYyODc4Mn0.BF-r05APjQhnDdqD_gkam5x4Tr1VH8z4oNys7d-WehY

instagram.user.id=17841441353836928
instagram.access.token=EAASBmp8pURsBRW8GlmCQRu4161xaLwcDZBsULtkuVLaMoov86p2yuaXSc6MvfdjL5celHcQua7IRPJDPdCTlGx3NqCObA0KZA0RdeA7H2tEAhn8aMyVKfuwvxiz5KNc7exTr0F8z4PYb7mAwMxO0J2lWa0NGoQf5lNuEwsjuQxL2sswCrEV6F5AQZBo
server.port=8080
app.public-url=https://nurture-earmuff-autism.ngrok-free.dev
