supabase.url=${SUPABASE_URL:https://scwvalydghoynskqliqo.supabase.co}
supabase.anon-key=${SUPABASE_ANON_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjd3ZhbHlkZ2hveW5za3FsaXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNTI3ODIsImV4cCI6MjA5MDYyODc4Mn0.BF-r05APjQhnDdqD_gkam5x4Tr1VH8z4oNys7d-WehY}
instagram.user.id=${INSTAGRAM_USER_ID:17841441353836928}
instagram.access.token=${INSTAGRAM_TOKEN:EAASBmp8pURsBRW8GlmCQRu4161xaLwcDZBsULtkuVLaMoov86p2yuaXSc6MvfdjL5celHcQua7IRPJDPdCTlGx3NqCObA0KZA0RdeA7H2tEAhn8aMyVKfuwvxiz5KNc7exTr0F8z4PYb7mAwMxO0J2lWa0NGoQf5lNuEwsjuQxL2sswCrEV6F5AQZBo}
server.port=8080
app.public-url=${APP_PUBLIC_URL:https://thevilnius-bot.onrender.com}
gemini.api-key=${GEMINI_API_KEY:AIzaSyCmkArodYyKgmXDB7LwRr7F1p99G5dG0Vw}
